### PR TITLE
Fix issue #20: create a template for PRs

### PR DESCRIPTION
**Pull request by tibo-mllr**
Fix issue #20 creating a PR template to make it easier and quicker to create a **_good_** PR.

### CODE REVIEW

**Comment by tibo-mllr** [comment]
It doesn't seem to already work while the file is only on this branch... Will try for real once merged, if it doesn't work I'll revert.

**Comment by tibo-mllr** [comment]
Pipeline failed because of a vulnerability... Will update packages when updates are available.

**Comment by AlexandreCGithub** [comment]
Must be very recent since pull request #26 wasn't affected

**Comment by tibo-mllr** [comment]
> Must be very recent since pull request #26 didn't fail the checks

Yep, 3 days ago: https://github.com/advisories/GHSA-3xgq-45jj-v275

**Comment by carlrizk** [comment]
> Pipeline failed because of a vulnerability... Will update packages when updates are available.

I suggest you disable the vulnerability check in the CI.
While its appreciated that you audit for vulnerabilities, its more important that you don't get blocked during your limited work time.

**Comment by tibo-mllr** [comment]
> > Pipeline failed because of a vulnerability... Will update packages when updates are available.
> 
> I suggest you disable the vulnerability check in the CI. While its appreciated that you audit for vulnerabilities, its more important that you don't get blocked during your limited work time.

Okay, will do!

**Review by AlexandreCGithub — APPROVED** [review]
Review:
- PR template: ok. Will maybe be extended during the project
- Vulnerability scan was disabled as discussed

**Pull request merged**
