### PR TITLE
Create React app

### PR DESCRIPTION
**Pull request by tibo-mllr**
Create and setup a React app using Next.js

Will fix:
- #5 
- #6 
- #7

### CODE REVIEW

**Comment by tibo-mllr** [comment]
Open to any changes in ESLint or prettier rules !
@TimotheeVrg @AlexandreCGithub @carlrizk

**Comment by tibo-mllr** [comment]
Now also fixes #2 and #4

**Comment by tibo-mllr** [comment]
Should I also update `eslint` to latest Major version @carlrizk ? The mandatory flat config usually makes me sick, but here it's a small project for the moment so I can try

**Comment by carlrizk** [comment]
> Should I also update `eslint` to latest Major version @carlrizk ? The mandatory flat config usually makes me sick, but here it's a small project for the moment so I can try

Yes, if you think its a good improvement to do.
You and your team are owner of the code and can do whatever you feel is better for your project.

**Comment by AlexandreCGithub** [comment]
Everything seems good to me.
Ok for version 8

**Review by AlexandreCGithub — APPROVED** [review]
Everything is OK for me, merge accepted

**Comment by TimotheeVrg** [comment]
Seems fine to me (for eslint, prettier rules and everything else), I'll approve too!

**Review by TimotheeVrg — APPROVED** [review]

**Pull request merged**
